{% set version = "0.6.13" %}
{% set version_major = version.rsplit('.', 1)[0] %}
{% set sha256 = "767ec234ae7aa684695b3a735548224888132e063f92db585759b422570621d4" %}

package:
  name: libcroco
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/gnome/sources/libcroco/{{ version_major }}/libcroco-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - pkg-config
    - {{ compiler('c') }}
  host:
    - glib
    - libxml2
  run:
    - glib
    - libxml2

test:
  commands:
    - test -f $PREFIX/lib/libcroco-{{ version_major }}$SHLIB_EXT
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.linuxfromscratch.org/blfs/view/svn/general/libcroco.html
  license: LGPL
  license_file: COPYING
  summary: a standalone CSS2 parsing and manipulation library

extra:
  recipe-maintainers:
    - jenzopr
    - pkgw
