travis:
  secure:
    BINSTAR_TOKEN: MCYfEdfP/NT1w79/Z89LrTbS9KS527fsfVNxtDz25IPIyGqN6sbsdQlcHbfegLJFMCb+cpFpXQfQ9Onf8fWOc/MUVNi+NNOY68XNwOPBQm926nvByWBk90gaQ+hHVgj4Tu+2q1hmkHPfgmKpxHVQ98irzuaaFBeRQQxeHvHJDBk+8g+KLIVVAJhBBkpcw49YVsUxo4WDe5lcQLSovLZLBv7/PNp6ZlytXti/gljcoSpphyDJquV1FsyxLvok+ltz3rRRsBZn6RII5KTnLbrLZ8JwHUu3Zy1FDA8L54XjB7dRUvR74YHy4pCI7bndZ02LVL1sWMI4Qor4QCBPsTnvc/te+0V90qCvHqjrpYfXKmoab5fKAb2VRuqy4nTbnF6jHDZ+DB0TW6+4PgYIY+nprqyDKiUZleTQhSuP8Bgtb+IsLYfneRZsM1asnS4EZjClp17Ke9ebiC86Mh0u5npcbtBQcxUCGa+Y9zJ8SQbBw5Q1NeqdsO1ZpSIv6Hf8NCenLS0kNzQAMLx687jOMyW0QE27/9eC0mLMWG+MUad4s1UyNBq7it+gn5xNviwKtWSSaGjhn9chX4WzmyVc2Y98cAfS7wvdpU6uqQVVqcvyghHOXi6DlxSv22eWW337hjm9z7QjHMB+w9zawradgShHnj8S7ATkh2E4IJxi+CoXR2E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
