appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: CQVF4Hxnp1gHc6yoKpf06BGi50VbhcumJ5TjXdS6Zqn3TRp36wGxdF6KS7HJlI5BvC0jhDjgiPmygWOGP6ot/vPzIiIRWuCnD39OONFxd+TELmnCCeq8PI+XmbVBR8wb1BCK0azjKfpCT7JKOj0tPEdZIRCz3TvJ3/nNFsud5uyJAtZwoKN7WYQHayCdzhrpKilwZHUj/oScQM0c5mWEYL8rQU8+mvFtEqakNVR+XU4yFe5q6/LcuSLfOaYvOUh0Nq+tT0QqIT1adxvekLRSiRHxmyXgmk6BYkmX0gk15pMPvKtNRA6pEV8I/jdhLQwNL1RlkkvMxUOZVWnHkBakpvZFb+mk8W+k7NbEf42UBFh2cNACJCIV0LN8FWELPuMp7wemlS/S8QXdJi51G1VJYJmckhFo6+vFfJB1L70ThJz+0bZaKauIE6eOGC+oUdY5+GTcKNeKKMgfHbStNs38eu77O3BPgi5+F0cjciamYszv8fjXpOHDSWgy8KKip1ss4ly21WnvH8Wzxnn35XNjZAr8dl8xDx4mjIGolDMtEJrGongM7lUL7ECb3nTeBMbwHHt/P/U2/k1Q9v52z1YetAFoolq1ZrgLXiwMdSRzsPAnmqc0VLpj5BDCUL4WxCroZhgXOdtJMWIVoJSBpAHZ19f5sfJOc2uSTwKH1ZCIbo0=}
